version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: car_data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      - DATABASE_HOST=db
      - DATABASE_NAME=car_data
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=123
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
    depends_on:
      - db
      - selenium
    volumes:
      - ./dumps:/app/dumps

  selenium:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  db_data:
